### ISSUE TITLE
When training from scratch on ian3 scene does not converge

### ISSUE THREAD

**Issue by tb2-sy** [wei-mao-2019/SDFFlow#1]
GOOD JOB! I tried training the model from scratch, but the results I got were strange. Is there something wrong?
This is training script:
`GPU=0
CUDA_VISIBLE_DEVICES=$GPU python training/exp_runner.py --conf ./confs/pretrain_flow.conf --gpu 0 --nepoch 2000 --is_pretrain_flow`
This train result:
![image](https://github.com/wei-mao-2019/SDFFlow/assets/61854446/8f2497ea-55f3-4159-acd3-c079edd6caa5)

**Comment by m43** [comment]
The result is expected since the pretraining is not training on `ian3` but on a dummy ball that grows from 0.5m to 1.0m, see [here](https://github.com/wei-mao-2019/SDFFlow/blob/5eca9398edc00ca29874662be17172abc5479d39/code/training/volsdf_train.py#L651-L673). Then the next step after pretraining would use those pretrained network weights (defined [here](https://github.com/wei-mao-2019/SDFFlow/blob/5eca9398edc00ca29874662be17172abc5479d39/code/confs/total_capture.conf#L12)) to train on a real scene.

For me, revising the `run.sh` as below worked well in getting reasonable results on the `hanggling_ b2` scene, I've also added a few comments based on my understanding:
```bash
# 1. Pre-training of the SDF Flow: Train on a dummy sphere that grows from radius 0.5 to 1.0 over the time horizon.
python -m training.exp_runner --conf confs/pretrain_flow.conf --gpu 0 --nepoch 2000 --is_pretrain_flow


# 2. Train the SDF Flow on a scane in the Total Capture dataset (the scene id is defined in the config)
python -m training.exp_runner --conf confs/total_capture.conf --gpus 2 --nepoch 2000 --is_dist --cancel_vis


# 3. Evaluate the trained SDF Flow

# 3.1. Create .ply files for the predicted geometry.
#         My results were saved to exps/total_capture_hanggling_b2/2024_04_24_10_31_25/runconf.conf
#         And I had stopped the training in step 2 after 300 epochs (as it was quite slow)
#         So I evaluate the checkpoint for epoch 300
#         But the results already look reasonable (qualitatively and quantitatively)
python -m training.exp_runner --conf exps/total_capture_hanggling_b2/2024_04_24_10_31_25/runconf.conf  --gpu 0 --cancel_vis --is_only_plot --is_continue --checkpoint 300

# 3.2. Evaluate the predicted geometry
python -m evaluation.eval_flow_geo --conf exps/total_capture_hanggling_b2/2024_04_24_10_31_25/runconf.conf --checkpoint 300 --timestamp 2024_04_24_10_31_25

# After 300 epochs:
# Mean Accuracy: 9.314097464084625
# Mean Completeness: 22.686426527798176
```

**Comment by tb2-sy** [comment]
> The result is expected since the pretraining is not training on `ian3` but on a dummy ball that grows from 0.5m to 1.0m, see [here](https://github.com/wei-mao-2019/SDFFlow/blob/5eca9398edc00ca29874662be17172abc5479d39/code/training/volsdf_train.py#L651-L673). Then the next step after pretraining would use those pretrained network weights (defined [here](https://github.com/wei-mao-2019/SDFFlow/blob/5eca9398edc00ca29874662be17172abc5479d39/code/confs/total_capture.conf#L12)) to train on a real scene.
> 
> For me, revising the `run.sh` as below worked well in getting reasonable results on the `hanggling_ b2` scene, I've also added a few comments based on my understanding:
> 
> ```shell
> # 1. Pre-training of the SDF Flow: Train on a dummy sphere that grows from radius 0.5 to 1.0 over the time horizon.
> python -m training.exp_runner --conf confs/pretrain_flow.conf --gpu 0 --nepoch 2000 --is_pretrain_flow
> 
> 
> # 2. Train the SDF Flow on a scane in the Total Capture dataset (the scene id is defined in the config)
> python -m training.exp_runner --conf confs/total_capture.conf --gpus 2 --nepoch 2000 --is_dist --cancel_vis
> 
> 
> # 3. Evaluate the trained SDF Flow
> 
> # 3.1. Create .ply files for the predicted geometry.
> #         My results were saved to exps/total_capture_hanggling_b2/2024_04_24_10_31_25/runconf.conf
> #         And I had stopped the training in step 2 after 300 epochs (as it was quite slow)
> #         So I evaluate the checkpoint for epoch 300
> #         But the results already look reasonable (qualitatively and quantitatively)
> python -m training.exp_runner --conf exps/total_capture_hanggling_b2/2024_04_24_10_31_25/runconf.conf  --gpu 0 --cancel_vis --is_only_plot --is_continue --checkpoint 300
> 
> # 3.2. Evaluate the predicted geometry
> python -m evaluation.eval_flow_geo --conf exps/total_capture_hanggling_b2/2024_04_24_10_31_25/runconf.conf --checkpoint 300 --timestamp 2024_04_24_10_31_25
> 
> # After 300 epochs:
> # Mean Accuracy: 9.314097464084625
> # Mean Completeness: 22.686426527798176
> ```

Thank you for your answer, I get it!
