### ISSUE TITLE
The confusion of training time

### ISSUE THREAD

**Issue by tb2-sy** [wei-mao-2019/SDFFlow#3]
Thank you for your excellent work! In your paper, you wrote "We train our model for 2000 epochs, which takes around 7 days on 2 NVIDIA 4090 GPUs for ten 1920 x 1080 videos of 24 frames." Before running the code, I thought this was the sum of the training times for all scenes, but when I experimented with two A40 images, I found that it seemed like this was the training time for one scene?

**Comment by wei-mao-2019** [comment]
Yes, it is for one scene.

**Comment by tb2-sy** [comment]
I got it, thanks.
