### ISSUE TITLE
optical flow supervise on the CMU Panoptic dataset

### ISSUE THREAD

**Issue by tb2-sy** [wei-mao-2019/SDFFlow#4]
Thanks for the nice work!
The method you proposed has achieved very good results on the CMU Panoptic dataset. What puzzles me is that why not use the optical flow obtained by RAFT as gt to supervise when training on the CMU Panoptic dataset?

**Comment by wei-mao-2019** [comment]
Thank you for your interests. We do tried to use the optical flow supervision on CMU dataset. However, we found that such supervision only shows very limited influence on the final geometry although the scene flow seems to be improved. There are a few factors that may lead to such effect: 1) the noisy optical flow 2) the complex scene motion may require extra regularisation on the scene flow. For synthesis data where the motion is simpler and with GT optical flow, the effects of optical flow regularisation is much more obvious.

**Comment by tb2-sy** [comment]
Thanks for your answer!
