### ISSUE TITLE
statistical values ​​ confusion about table 1

### ISSUE THREAD

**Issue by tb2-sy** [wei-mao-2019/SDFFlow#5]
Thanks for your nice work!
We are following your work, and I am confused about the statistical values ​​in your table, (15.8+13.5+17.2+16.1+13.7)/5=15.26, but the average value of Ours in Table 1 is 15.2. Do you always round down the avg values ​​in the table instead of rounding them up? But for Tensor4D，(19.1+19.5+23.2+22.9+20.7+21.1) = 21.08, in your table is 21.10. 
Is there any discrepancy between my current statistical method and yours?

**Comment by wei-mao-2019** [comment]
Hi, 

Thank you for your interests. 

I think this is because that the average is computed with the raw value for each scene and then rounded to 1 decimals. The values you have here is the average of the rounded value for each scene.

Cheers

**Comment by tb2-sy** [comment]
Thanks!
