### ISSUE TITLE
Mesh Generation

### ISSUE THREAD

**Issue by aaryapatel007** [wei-mao-2019/SDFFlow#6]
Hi @wei-mao-2019,

Thanks for your fantastic work.

I saw that you did visual mesh reconstruction comparisons with NDR and Tensor4D models. I was curious to know how you generated mesh from Tensor4D, which does not provide the mesh generation code in their GitHub nor show meshes in their paper.

If possible, can you please share the modified code with mesh generation from the Tensor4D model?

**Comment by wei-mao-2019** [comment]
Hi, Thank you for your interests. I currently do not have the visulization code for Tensor4D but it is pretty simple we just use marching cube to extract the geometry which is the same as ours.
